export const data = [
    {
      id: crypto.randomUUID(),
      image: "./assets/book1.png",
      title: "JavaScript and Jquery",
      author: "Jon Duckett",
      price: 62,
      rating: 4,
      isFavorite: true,
      publishYear: 2014,
    },
    {
      id: crypto.randomUUID(),
      image: "./assets/book2.png",
      title: "Eloquent JavaScript",
      author: "Marijn Haverbeke",
      price: 35,
      rating: 5,
      isFavorite: false,
      publishYear: 2018,
    },
    {
      id: crypto.randomUUID(),
      image: "./assets/book3.png",
      title: "You Don't Know JS: Scope & Closures",
      author: "Kyle Simpson",
      price: 45,
      rating: 3,
      isFavorite: true,
      publishYear: 2015,
    },
    {
      id: crypto.randomUUID(),
      image: "./assets/book4.png",
      title: "Learning React",
      author: "Alex Banks and Eve Porcello",
      price: 50,
      rating: 4,
      isFavorite: false,
      publishYear: 2020,
    },
    {
      id: crypto.randomUUID(),
      image: "./assets/book5.png",
      title: "JavaScript: The Good Parts",
      author: "Douglas Crockford",
      price: 30,
      rating: 5,
      isFavorite: true,
      publishYear: 2008,
    },
    {
      id: crypto.randomUUID(),
      image: "./assets/book6.png",
      title: "Professional JavaScript for Web Developers",
      author: "Nicholas C. Zakas",
      price: 70,
      rating: 4,
      isFavorite: false,
      publishYear: 2012,
    },
    {
      id: crypto.randomUUID(),
      image: "./assets/book7.png",
      title: "Secrets of the JavaScript Ninja",
      author: "John Resig and Bear Bibeault",
      price: 55,
      rating: 2,
      isFavorite: true,
      publishYear: 2016,
    },
    {
      id: crypto.randomUUID(),
      image: "./assets/book8.png",
      title: "JavaScript: The Definitive Guide",
      author: "David Flanagan",
      price: 80,
      rating: 5,
      isFavorite: true,
      publishYear: 2020,
    },
    {
      id: crypto.randomUUID(),
      image: "./assets/book9.png",
      title: "Effective JavaScript",
      author: "David Herman",
      price: 40,
      rating: 4,
      isFavorite: false,
      publishYear: 2012,
    },
    {
      id: crypto.randomUUID(),
      image: "./assets/book10.png",
      title: "JavaScript Patterns",
      author: "Stoyan Stefanov",
      price: 35,
      rating: 3,
      isFavorite: true,
      publishYear: 2010,
    },
  ];
  